import Link from "next/link";
import "./globals.css";
import styles from './page.module.css'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <section className={styles.top}>
          <Link href={"/"}>
            <h1>Hoodie's blog</h1>
          </Link>
          <nav>
            <ul>
              <Link href={"/"}>
                <li>home</li>
              </Link>
              <Link href={"/about"}>
                <li>about</li>
              </Link>
              <Link href={"/posts"}>
                <li>posts</li>
              </Link>
              <Link href={"/contact"}>
                <li>contact</li>
              </Link>
            </ul>
          </nav>
        </section>
        {children}
        <footer className={styles.footer}>hello everyone</footer>
      </body>
    </html>
  );
}
